-- Criação da tabela de viagens
CREATE TABLE public.viagens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    turno TEXT NOT NULL,
    embarque TEXT NOT NULL,
    desembarque TEXT NOT NULL,
    lotacao INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Ativar Row Level Security (RLS) para a tabela
ALTER TABLE public.viagens ENABLE ROW LEVEL SECURITY;

-- Criar política para permitir inserções públicas (usuários anônimos)
-- Isso é necessário porque o formulário não exige login
CREATE POLICY "Permitir insercoes anonimas" 
ON public.viagens 
FOR INSERT 
TO anon 
WITH CHECK (true);
