-- Criação da tabela de viagens
CREATE TABLE public.viagens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    turno TEXT NOT NULL,
    embarque TEXT NOT NULL,
    desembarque TEXT NOT NULL,
    lotacao INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Ativar Row Level Security (RLS) para a tabela
ALTER TABLE public.viagens ENABLE ROW LEVEL SECURITY;

-- Criar política para permitir inserções públicas (usuários anônimos)
-- Isso é necessário porque o formulário não exige login
CREATE POLICY "Permitir insercoes anonimas" 
ON public.viagens 
FOR INSERT 
TO anon 
WITH CHECK (true);

-- ========== TABELAS DE TURNOS E PARADAS (rotas do transporte) ==========

-- Turnos (Manhã 1, Manhã 2, Tarde 1, Tarde 2, Noite 1, Noite 2)
CREATE TABLE public.turnos (
    id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    label TEXT NOT NULL,
    horario TEXT NOT NULL,
    onibus TEXT NOT NULL
);

-- Paradas por turno (cada linha = uma parada em uma rota, com ordem)
CREATE TABLE public.paradas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    turno_id SMALLINT NOT NULL REFERENCES public.turnos(id) ON DELETE CASCADE,
    nome TEXT NOT NULL,
    ordem SMALLINT NOT NULL
);

ALTER TABLE public.turnos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.paradas ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Ler turnos" ON public.turnos FOR SELECT TO anon USING (true);
CREATE POLICY "Ler paradas" ON public.paradas FOR SELECT TO anon USING (true);

-- Índices para consultas por turno
CREATE INDEX idx_paradas_turno_id ON public.paradas(turno_id);
CREATE INDEX idx_paradas_turno_ordem ON public.paradas(turno_id, ordem);

-- ========== SEED: Turnos ==========
INSERT INTO public.turnos (slug, label, horario, onibus) VALUES
('manha_1', 'Manhã 1 (6h–8h)', '6h–8h', 'Ônibus A, B, C, D'),
('manha_2', 'Manhã 2 (9h–10h)', '9h–10h', 'Ônibus B (segunda viagem)'),
('tarde_1', 'Tarde 1 (11h–13h)', '11h–13h', 'Ônibus A, B, C, D, E, F'),
('tarde_2', 'Tarde 2 (14h–16h)', '14h–16h', 'Ônibus B, C, D (ida) + A, B, C, D (retorno)'),
('noite_1', 'Noite 1 (17h–18h)', '17h–18h', 'Ônibus C, G, H (retorno CCA→Juazeiro)'),
('noite_2', 'Noite 2 (18h–23h)', '18h–23h', 'Ônibus E, F, J, L');

-- ========== SEED: Paradas por turno ==========
-- Manhã 1 (id 1)
INSERT INTO public.paradas (turno_id, nome, ordem) VALUES
(1, 'UNIVASF Campus Juazeiro', 1),
(1, 'Estação Velha Juazeiro', 2),
(1, 'Verdão Juazeiro', 3),
(1, 'Posto Raul Lins / Bairro Castelo Branco', 4),
(1, 'Ponto de ônibus próximo a Lucas Pneus', 5),
(1, 'GBarbosa Juazeiro', 6),
(1, 'Canteiro de Obras Juazeiro', 7),
(1, 'Terminal de Juazeiro – Camelódromo 2 de Julho', 8),
(1, 'UNIVASF Campus Petrolina', 9),
(1, 'Supermercado Regente', 10),
(1, 'BR 407 – Isaías Automóveis / Posto Delta', 11),
(1, 'Feira da COHAB Massangano', 12),
(1, 'Izabela Construções (Cosme Damião / sentido CCA)', 13),
(1, 'Banco Itaú – Av. Guararapes', 14),
(1, 'Praça das Algarobas – Av. Guararapes', 15),
(1, 'GBarbosa Av. Monsenhor Ângelo Sampaio', 16),
(1, 'Ponto BR 428 – Sucatão Moraes (Loteamento Recife)', 17),
(1, 'Ponto BR 428 – DR Distribuidora (Vila Marcela)', 18),
(1, 'Av. Transnordestina – AMR Areias', 19),
(1, 'Av. Transnordestina – Entrada Bairro Dom Avelar', 20),
(1, 'Av. Transnordestina – Mecânica Eduardo / Bairro São Joaquim', 21),
(1, 'Av. Transnordestina – Posto de Combustível / Bairro Pedra Linda', 22),
(1, 'Av. Transnordestina – Nutiva Agro', 23),
(1, 'Av. da Integração – Secretaria de Obras', 24),
(1, 'Av. da Integração – Sementeira', 25),
(1, 'Av. da Integração – Petrape', 26),
(1, 'Plante Bem', 27),
(1, 'Distribuidora de Bebidas Revalle', 28),
(1, 'Academia Well', 29),
(1, 'Antigo Bar da Tripa – Av. Monsenhor Ângelo Sampaio', 30),
(1, 'Clínica Popular Av. São Francisco (Areia Branca)', 31),
(1, 'Canteiro de Obras Av. 7 de Setembro', 32),
(1, 'Posto São Francisco Av. 7 de Setembro', 33),
(1, 'Estrada da Banana – Restaurante Dona Branca', 34),
(1, 'Estrada da Banana – Antiga Distribuidora Camaleão', 35),
(1, 'Residência Estudantil CCA', 36),
(1, 'UNIVASF Campus Ciências Agrárias – Bloco Antigo', 37),
(1, 'Hospital Veterinário CCA', 38),
(1, 'Bloco de Salas de Aula CCA', 39);

-- Manhã 2 (id 2)
INSERT INTO public.paradas (turno_id, nome, ordem) VALUES
(2, 'UNIVASF Campus Juazeiro', 1),
(2, 'Terminal de Juazeiro – Camelódromo 2 de Julho', 2),
(2, 'UNIVASF Campus Petrolina', 3),
(2, 'GBarbosa Av. Monsenhor Ângelo Sampaio', 4),
(2, 'Secretaria de Obras', 5),
(2, 'Sementeira', 6),
(2, 'Petrape', 7),
(2, 'Feira da COHAB Massangano', 8),
(2, 'BR 407 – Izabela Construções', 9),
(2, 'Residência Estudantil CCA', 10),
(2, 'UNIVASF Campus CCA – Bloco Antigo', 11),
(2, 'Hospital Veterinário', 12),
(2, 'Bloco de Salas de Aula CCA', 13);

-- Tarde 1 (id 3)
INSERT INTO public.paradas (turno_id, nome, ordem) VALUES
(3, 'UNIVASF Campus Juazeiro', 1),
(3, 'Estação Velha Juazeiro', 2),
(3, 'Verdão Juazeiro', 3),
(3, 'Posto Raul Lins / Bairro Castelo Branco', 4),
(3, 'GBarbosa Juazeiro', 5),
(3, 'Canteiro de Obras Juazeiro', 6),
(3, 'Terminal de Juazeiro – Camelódromo 2 de Julho', 7),
(3, 'UNIVASF Campus Petrolina', 8),
(3, 'Supermercado Regente', 9),
(3, 'Secretaria de Obras – Av. da Integração', 10),
(3, 'Sementeira – Av. da Integração', 11),
(3, 'Petrape – Av. da Integração', 12),
(3, 'Av. da Integração – Mundo da Lua', 13),
(3, 'GBarbosa Av. Monsenhor Ângelo Sampaio', 14),
(3, 'Ministério Público Federal', 15),
(3, 'Av. Transnordestina – Nutiva Agro', 16),
(3, 'Av. Transnordestina – Posto Pedra Linda', 17),
(3, 'Av. Transnordestina – Mecânica Eduardo / São Joaquim', 18),
(3, 'Av. Transnordestina – Entrada Dom Avelar', 19),
(3, 'Av. Transnordestina – AMR Areias', 20),
(3, 'Ponto BR 428 – DR Distribuidora (Vila Marcela)', 21),
(3, 'Ponto BR 428 – Sucatão Moraes (Loteamento Recife)', 22),
(3, 'Ponto BR 428 – Posto de Mola Santa Clara', 23),
(3, 'Estação Velha / Cooperativa Brasil', 24),
(3, 'Farmácia Popular', 25),
(3, 'Posto Raul Lins – Entrada Castelo Branco', 26),
(3, 'Rua do Paraíso ao lado das Lojas Americanas', 27),
(3, 'Feira da COHAB Massangano', 28),
(3, 'BR 407 – Izabela Construções', 29),
(3, 'Plante Bem', 30),
(3, 'Estrada da Banana – Condomínio Mais Viver', 31),
(3, 'Estrada da Banana – Restaurante Dona Branca', 32),
(3, 'Estrada da Banana – Antiga Distribuidora Camaleão', 33),
(3, 'Av. 7 de Setembro – Aldiegas', 34),
(3, 'Mecânica Ouro Diesel – Av. 7 de Setembro', 35),
(3, 'Delegacia de Polícia Civil – Ouro Preto', 36),
(3, 'Academia I9 – Av. 7 de Setembro', 37),
(3, 'Residência Estudantil CCA', 38),
(3, 'UNIVASF Campus CCA – Bloco Antigo', 39),
(3, 'Hospital Veterinário', 40),
(3, 'Bloco de Salas de Aula CCA', 41);

-- Tarde 2 (id 4)
INSERT INTO public.paradas (turno_id, nome, ordem) VALUES
(4, 'UNIVASF Campus Juazeiro', 1),
(4, 'Terminal de Juazeiro – Camelódromo 2 de Julho', 2),
(4, 'UNIVASF Campus Petrolina', 3),
(4, 'Sementeira – Av. da Integração', 4),
(4, 'Petrape – Av. da Integração', 5),
(4, 'Secretaria de Obras – Av. da Integração', 6),
(4, 'GBarbosa Petrolina – Av. Monsenhor Ângelo Sampaio', 7),
(4, 'Canteiro de Obras – Av. 7 de Setembro', 8),
(4, 'Posto São Francisco – Av. 7 de Setembro', 9),
(4, 'Feira da COHAB Massangano', 10),
(4, 'BR 407 – Izabela Construções', 11),
(4, 'Plante Bem', 12),
(4, 'Supermercado Regente', 13),
(4, 'Rua do Paraíso ao lado das Lojas Americanas', 14),
(4, 'Residência Estudantil CCA', 15),
(4, 'UNIVASF Campus CCA – Bloco Antigo', 16),
(4, 'Hospital Veterinário', 17),
(4, 'Bloco de Salas de Aula CCA', 18);

-- Noite 1 (id 5)
INSERT INTO public.paradas (turno_id, nome, ordem) VALUES
(5, 'UNIVASF Campus CCA', 1),
(5, 'Bloco de Salas de Aula CCA', 2),
(5, 'Hospital Veterinário', 3),
(5, 'Bloco Antigo CCA', 4),
(5, 'Residência Estudantil CCA', 5),
(5, 'BR 407 – Izabela Construções', 6),
(5, 'Feira da COHAB Massangano', 7),
(5, 'Igreja Filadélfia', 8),
(5, 'Costrutéo (ponto de ônibus)', 9),
(5, 'Posto ALE', 10),
(5, 'Plante Bem', 11),
(5, 'Petrape', 12),
(5, 'Sementeira', 13),
(5, 'Parque Mundo da Lua', 14),
(5, 'UNIVASF Campus Petrolina', 15),
(5, 'Supermercado Regente', 16),
(5, 'Av. Transnordestina – Nutiva Agro', 17),
(5, 'Av. Transnordestina – Posto Pedra Linda', 18),
(5, 'Av. Transnordestina – Mecânica Eduardo / São Joaquim', 19),
(5, 'Av. Transnordestina – Entrada Dom Avelar', 20),
(5, 'Av. Transnordestina – AMR Areias', 21),
(5, 'Ponto BR 428 – PRF', 22),
(5, 'Ponto BR 428 – Distribuidora / Vila Débora', 23),
(5, 'Ponto BR 428 – Posto Carranca', 24),
(5, 'Ponto BR 428 – DETRAN', 25),
(5, 'GBarbosa Av. Monsenhor Ângelo Sampaio', 26),
(5, 'Ministério Público Federal', 27),
(5, 'Estação Velha / Cooperativa Brasil', 28),
(5, 'Farmácia Popular', 29),
(5, 'Verdão Juazeiro', 30),
(5, 'Posto Raul Lins – Entrada Castelo Branco', 31),
(5, 'GBarbosa Juazeiro – Av. Adolfo Viana', 32),
(5, 'Canteiro de Obras Juazeiro', 33),
(5, 'Terminal de Juazeiro – Camelódromo 2 de Julho', 34),
(5, 'Rua do Paraíso ao lado das Lojas Americanas', 35),
(5, 'UNIVASF Campus Juazeiro', 36),
(5, 'Mecânica Ouro Diesel', 37),
(5, 'Delegacia de Polícia Civil – Ouro Preto', 38),
(5, 'Academia I9', 39),
(5, 'DETRAN – Av. Monsenhor (via principal)', 40);

-- Noite 2 (id 6)
INSERT INTO public.paradas (turno_id, nome, ordem) VALUES
(6, 'UNIVASF Campus Juazeiro', 1),
(6, 'Terminal de Juazeiro – Camelódromo 2 de Julho', 2),
(6, 'Rodoviária de Petrolina', 3),
(6, 'UNIVASF Campus Petrolina', 4),
(6, 'Supermercado Regente', 5),
(6, 'Sementeira', 6),
(6, 'Mundo da Lua', 7),
(6, 'Caixa d''Água da COMPESA', 8),
(6, 'Antigo Bar da Tripa – Av. Monsenhor Ângelo Sampaio', 9),
(6, 'GBarbosa Petrolina', 10),
(6, 'Posto de Gasolina Big Brother', 11),
(6, 'Canteiro de Obras', 12),
(6, 'Ponto em frente à Abaré', 13),
(6, 'Ponto Aldiegas', 14),
(6, 'Posto São Francisco', 15),
(6, 'Feira da COHAB Massangano', 16),
(6, 'Final da proteção de metal – Bairro Quati', 17),
(6, 'BR 407 – Izabela Construções', 18),
(6, 'Residência Estudantil CCA', 19),
(6, 'Igreja Filadélfia', 20),
(6, 'Costrutéo (ponto de ônibus)', 21),
(6, 'Posto ALE', 22),
(6, 'Plante Bem', 23),
(6, 'Petrape', 24),
(6, 'Parque Mundo da Lua', 25),
(6, 'Estação Velha / Cooperativa Brasil', 26),
(6, 'Farmácia Popular', 27),
(6, 'Verdão Juazeiro', 28),
(6, 'Posto Raul Lins – Entrada Castelo Branco', 29),
(6, 'Equipadora Cordeiro', 30),
(6, 'Parque Lagoa de Calú', 31),
(6, 'Canteiro de Obras – Juazeiro', 32),
(6, 'Rua do Paraíso ao lado das Lojas Americanas', 33),
(6, 'Secretaria de Obras – Av. da Integração', 34),
(6, 'Escola Clementino Coelho', 35),
(6, 'Zenilton Automóveis', 36),
(6, 'Del Veículos', 37),
(6, 'Mecânica Ouro Diesel', 38),
(6, 'Delegacia da Polícia Civil – Ouro Preto', 39),
(6, 'Abaré', 40),
(6, 'Academia I9', 41),
(6, 'DETRAN – Av. Monsenhor', 42),
(6, 'Ministério Público', 43),
(6, 'Pousada Paraíso', 44),
(6, 'Entrada da COHAB 06 (Tapera)', 45);
